[package]
name = "orangepi-IA"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.40", features = ["full"] }         # async runtime
tokio-tungstenite = "0.20"                                # WebSocket support
serde = { version = "1.0", features = ["derive"] }       # JSON serialization
serde_json = "1.0"                                       # JSON parsing
log = "0.4"                                              # logging
env_logger = "0.10"                                      # simple logger
tokio-serial = "5.4.5"
